#!/bin/env bash

alias o='open .'
alias s='subl .'
alias f='foreman start'
alias be='bundle exec'
alias fspec='be rspec --format progress --only-failures --fail-fast --order defined'

alias ∆='diff'

alias gitlog='clear;git log -40 --pretty=oneline;echo "... THE REST WERE CHOPPED OUT FOR BREVITY ..."'
alias git-ignore-mode="git config core.filemode false; git submodule foreach \"git config core.filemode false\""
alias git-conflicts="git diff --name-only | xargs grep -il '<<<<<<' | grep -v filter|uniq | xargs subl"
alias gsu="git submodule update --init --recursive"

alias show-open-ports='sudo lsof -i | grep LISTEN'        # openPorts:    All listening connections

# This one (credit @scryptmouse) can auto-jam your staged changes into a previous commit of your
# choice. It will leave your unstaged changes alone. Call it like this (once you've got your desired
# changes staged):
#  fixup [target-commit-ref]
alias fixup='!f() { TARGET=$(git rev-parse "$1"); git commit --fixup=$TARGET ${@:2} && EDITOR=true git rebase -i --autostash --autosquash $TARGET^; }; f'

alias git=hub

