#!/bin/env bash

alias o='open .'
alias s='subl .'
alias ss='subl Source/typo3conf/ext/t3site/Sites/'
alias sss='ss; Script/watch'
alias c='php Source/typo3/cli_dispatch.phpsh cleartypo3cache all'
alias i='/Applications/IntelliJ\ IDEA\ 14.app/Contents/MacOS/idea `pwd`'
alias be='bundle exec'

alias bb='subl /opt/boxen'
alias bbb='subl /opt/boxen/repo'

alias gitlog='clear;git log -40 --pretty=oneline;echo "... THE REST WERE CHOPPED OUT FOR BREVITY ..."'
alias git-unpushed='clear; git fetch --all; git log -40 --pretty=oneline origin/master..HEAD; echo "... THE REST WERE CHOPPED OUT FOR BREVITY ..."'
alias git-ignore-mode="git config core.filemode false; git submodule foreach \"git config core.filemode false\""
alias git-conflicts="git diff --name-only | xargs grep -il '<<<<<<' | grep -v filter|uniq | xargs subl"
alias gsu="git submodule update --init --recursive"

alias php-log='sudo tail -f /opt/boxen/log/php/*'
alias nginx-log='sudo tail -f /opt/boxen/log/nginx/*'
alias flush-dns="sudo discoveryutil udnsflushcaches"

alias ios='open /Applications/Xcode.app/Contents/Developer/Applications/iOS\ Simulator.app'
